-- ============================================================
-- Ôn luyện HSG Công nghệ — Schema Supabase (Postgres)
-- Chạy 1 lần trong Supabase Dashboard → SQL Editor → New query
-- Paste toàn bộ file này → Run
-- ============================================================

-- ---------- Bảng ----------
create table if not exists subjects (
  id text primary key,
  name text not null,
  code text
);

create table if not exists topics (
  id text primary key,
  subject_id text not null references subjects (id) on delete cascade,
  name text not null,
  grade int default 12
);

create table if not exists questions (
  -- BY DEFAULT (không phải ALWAYS) để script migrate giữ nguyên được ID cũ
  id bigint generated by default as identity primary key,
  subject_id text not null references subjects (id) on delete cascade,
  topic_id text references topics (id) on delete set null,
  grade int default 12,
  difficulty text default 'vận dụng',
  qtype text default 'trac_nghiem',
  content text not null,
  options jsonb default '[]'::jsonb,
  correct_answer text default '',
  explanation text default '',
  score float default 1,
  source text default 'mẫu',
  image_url text default '',
  created_at timestamptz default now()
);

create table if not exists exams (
  id bigint generated by default as identity primary key,
  title text default 'Đề',
  mode text default 'practice',
  duration_min int default 45,
  question_ids jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists attempts (
  id bigint generated by default as identity primary key,
  exam_id bigint references exams (id) on delete set null,
  mode text default 'practice',
  correct int default 0,
  total int default 0,
  accuracy float default 0,
  detail jsonb default '[]'::jsonb,
  student_name text default '',
  focus_exits int default 0,
  focus_log jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  name text not null,
  class_name text default '',
  team text default '',
  note text default '',
  created_at timestamptz default now()
);

-- ---------- Index cho 1200 HS + ngân hàng lớn ----------
create index if not exists idx_questions_subject on questions (subject_id);
create index if not exists idx_questions_topic on questions (topic_id);
create index if not exists idx_questions_grade on questions (grade);
create index if not exists idx_attempts_student on attempts (student_name);
create index if not exists idx_attempts_created on attempts (created_at desc);
create index if not exists idx_students_team on students (team);
create index if not exists idx_students_name on students (name);

-- ---------- RLS: mở cho lớp học thử nghiệm ----------
-- NOTE: bản thử nghiệm dùng anon key trực tiếp, chưa có đăng nhập,
-- nên mở policy cho phép đọc/ghi. Khi lên chính thức (có Auth),
-- thay bằng policy theo auth.uid() + role giáo viên/học sinh.
alter table subjects enable row level security;
alter table topics enable row level security;
alter table questions enable row level security;
alter table exams enable row level security;
alter table attempts enable row level security;
alter table students enable row level security;

drop policy if exists "open_all_subjects" on subjects;
drop policy if exists "open_all_topics" on topics;
drop policy if exists "open_all_questions" on questions;
drop policy if exists "open_all_exams" on exams;
drop policy if exists "open_all_attempts" on attempts;
drop policy if exists "open_all_students" on students;

create policy "open_all_subjects" on subjects for all using (true) with check (true);
create policy "open_all_topics" on topics for all using (true) with check (true);
create policy "open_all_questions" on questions for all using (true) with check (true);
create policy "open_all_exams" on exams for all using (true) with check (true);
create policy "open_all_attempts" on attempts for all using (true) with check (true);
create policy "open_all_students" on students for all using (true) with check (true);

-- ---------- Storage: bucket ảnh minh họa câu hỏi ----------
insert into storage.buckets (id, name, public)
values ('question-images', 'question-images', true)
on conflict (id) do nothing;

drop policy if exists "public_read_images" on storage.objects;
drop policy if exists "anon_upload_images" on storage.objects;
drop policy if exists "anon_delete_images" on storage.objects;

create policy "public_read_images" on storage.objects
  for select using (bucket_id = 'question-images');
create policy "anon_upload_images" on storage.objects
  for insert with check (bucket_id = 'question-images');
create policy "anon_delete_images" on storage.objects
  for delete using (bucket_id = 'question-images');
